# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'test1.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
import pygame


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(800, 781)
        # 帮助
        font = QtGui.QFont()
        font.setFamily(u"Agency FB")
        font.setBold(True)
        font.setWeight(75)
        self.help_button = QtWidgets.QToolButton(Form)
        self.help_button.setGeometry(QtCore.QRect(600, 630, 47, 21))
        self.help_button.setObjectName("help_button")
        self.help_button.setFont(font)
        # 开始的
        self.start_button = QtWidgets.QPushButton(Form)
        self.start_button.setGeometry(QtCore.QRect(320, 570, 141, 51))
        self.start_button.setObjectName("start_button")
        font1 = QtGui.QFont()
        font1.setFamily(u"Arial")
        font1.setPointSize(14)
        font1.setBold(True)
        font1.setWeight(75)
        self.start_button.setFont(font1)

        # 退出的
        self.exit_button = QtWidgets.QPushButton(Form)
        self.exit_button.setGeometry(QtCore.QRect(320, 640, 141, 51))
        self.exit_button.setObjectName("exit_button")
        self.exit_button.setFont(font1)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

        self.l1 = QtWidgets.QLabel(Form)
        png = QtGui.QPixmap("L0ATTB@K3{TVQKM6}5KDM6J.jpg")
        self.l1.setGeometry(QtCore.QRect(100, 20, 100, 100))
        self.l1.setPixmap(png)
        self.l1.setScaledContents(True)  # 自动适应
        self.l1.resize(600, 500)


        pygame.init()  # 起始界面背景音乐
        track = pygame.mixer.music.load(r"Various Artists - caromhall.mp3")
        pygame.mixer.music.play()

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "五子棋"))
        self.help_button.setText(_translate("Form", "帮助"))
        self.start_button.setText(_translate("Form", "开始游戏"))
        self.exit_button.setText(_translate("Form", "退出游戏"))
